### ISSUE TITLE
Add newlines and indentation to output c file.

### ISSUE THREAD

**Issue by Yhennon** [SamuelIvan99/lightweight-programming-language#12]

**Comment by Yhennon** [comment]
Currently the whole code is output as a single line of code. Of course that works, and we might now even care about the
output file as long as it works.

Just briefly discuss if indentation is needed. If not, we can remove this issue.

**Comment by Dragoshel** [comment]
> Currently the whole code is output as a single line of code. Of course that works, and we might now even care about the output file as long as it works.
> 
> Just briefly discuss if indentation is needed. If not, we can remove this issue.

Outputting the whole program won't give us any trouble with implementation, but it will be really bad for checking the c code for bugs/proper generation.
I was thinking that we could just use a code formatter to achieve the same function without actually having to implement it ourselves? What do you think?
